from .models import (
    AgentRole,
    BuildPhase,
    ModuleCard,
    SystemBlueprint,
    TrustZone,
)
from .rooms import PERMISSION_LEVELS, ROOM_REGISTRY


SYSTEM_BLUEPRINT = SystemBlueprint(
    mission=(
        "Build a supervised, local-first synthetic cognition stack where the clone interface "
        "emerges from governed modules instead of becoming a single unrestricted agent."
    ),
    hypervisor_answer=(
        "The hypervisor is a local software control plane: it routes tasks, enforces room "
        "permissions, records audit trails, exposes debug state, and keeps sensitive layers separated."
    ),
    trust_zones=[
        TrustZone(
            id="public",
            name="Public Knowledge",
            description="Open references, publications, public documentation, and external knowledge bases.",
            examples=["papers", "open datasets", "public docs"],
        ),
        TrustZone(
            id="personal",
            name="Personal Knowledge",
            description="User-owned media, notes, drawings, recordings, and file archives.",
            examples=["photos", "voice notes", "documents", "drawings"],
        ),
        TrustZone(
            id="intimate",
            name="Sensitive Cognition",
            description="Private memory, journals, conversations, and autobiographical continuity layers.",
            examples=["private chats", "journals", "memory episodes"],
        ),
        TrustZone(
            id="restricted_bio",
            name="Restricted Bio",
            description="Governed genomics, lineage references, structural biology, and high-risk interpretation.",
            examples=["raw DNA", "VCF files", "annotation sandboxes", "protein targets"],
        ),
    ],
    modules=[
        ModuleCard(
            id="mission-control",
            name="Mission Control",
            zone_id="public",
            supervisor="hypervisor",
            stage="active",
            status="operational",
            purpose="Unified cockpit for dataset intake, memory exploration, room registry, audit preview, and owner debug.",
            key_inputs=["module state", "audit stream", "dataset index", "room registry"],
            outputs=["mission view", "control summaries", "ingest commands", "memory context previews"],
        ),
        ModuleCard(
            id="hypervisor",
            name="Hypervisor Control Plane",
            zone_id="public",
            supervisor="root debugger",
            stage="active",
            status="operational",
            purpose="Route tasks, enforce permissions, maintain approvals, and prevent unsafe cross-module leakage.",
            key_inputs=["task requests", "room policy", "circadian state", "audit evidence"],
            outputs=["routing decisions", "approval gates", "debug visibility"],
        ),
        ModuleCard(
            id="rooms-layer",
            name="Rooms and Permissions",
            zone_id="public",
            supervisor="hypervisor",
            stage="phase-2a",
            status="registry_shell",
            purpose="Define governed collaboration spaces with explicit permissions, supervisors, and retention rules.",
            key_inputs=["agent identities", "room classifications", "permission levels"],
            outputs=["room registry", "access policies", "summary boundaries"],
        ),
        ModuleCard(
            id="memory-core",
            name="Memory Core",
            zone_id="intimate",
            supervisor="memory supervisor",
            stage="phase-2c4",
            status="read_only_operational",
            purpose="Preserve raw events, entity links, episodes, context packages, and bounded read-only answers with visible provenance.",
            key_inputs=["messages", "notes", "timeline events"],
            outputs=["event records", "episode candidates", "retrieval results", "context packages", "read-only answers"],
        ),
        ModuleCard(
            id="media-lake",
            name="Media Lake",
            zone_id="personal",
            supervisor="media supervisor",
            stage="phase-2a",
            status="indexing_foundation",
            purpose="Index images, audio, video, documents, archives, and generic files into searchable evidence layers.",
            key_inputs=["dataset roots", "file scans", "metadata extraction"],
            outputs=["indexed assets", "hashes", "type classification", "dedup groundwork", "preflight manifests"],
        ),
        ModuleCard(
            id="art-lab",
            name="Art and Drawing Lab",
            zone_id="personal",
            supervisor="art supervisor",
            stage="phase-2c",
            status="planned",
            purpose="Measure formal visual properties without drifting into personality or clinical inference.",
            key_inputs=["drawings", "visual archives", "image assets"],
            outputs=["formal metrics", "composition features", "longitudinal comparisons"],
        ),
        ModuleCard(
            id="genomics-lab",
            name="Genomics Lab",
            zone_id="restricted_bio",
            supervisor="genomics supervisor",
            stage="phase-2d",
            status="planned_sandbox",
            purpose="Keep raw DNA on a separate supervised pathway from memory, persona rendering, and general rooms.",
            key_inputs=["raw DNA", "variant files", "annotation references"],
            outputs=["normalized variants", "sandbox summaries", "approved findings"],
        ),
        ModuleCard(
            id="constitution-layer",
            name="Constitution Layer",
            zone_id="intimate",
            supervisor="hypervisor",
            stage="phase-2e",
            status="planned_shell",
            purpose="Store stable trait vectors, long-cycle biases, provenance, and approval state for slowly changing parameters.",
            key_inputs=["approved parameter updates", "lineage references", "version history"],
            outputs=["constitutional parameters", "change logs", "stable weights"],
        ),
        ModuleCard(
            id="circadian-layer",
            name="Circadian Layer",
            zone_id="public",
            supervisor="hypervisor",
            stage="phase-2f",
            status="planned_shell",
            purpose="Control wake, rest, consolidation, quiet windows, and maintenance timing as a system function.",
            key_inputs=["time signals", "light input", "workload state"],
            outputs=["mode switches", "maintenance windows", "routing influence"],
        ),
        ModuleCard(
            id="sensory-layer",
            name="Sensory Layer",
            zone_id="personal",
            supervisor="media supervisor",
            stage="phase-2f",
            status="planned_shell",
            purpose="Abstract visual, audio, text, file, and time-light inputs into sanitized system-level channels.",
            key_inputs=["visual_input", "audio_input", "text_input", "file_event_input", "time_light_input"],
            outputs=["sanitized signals", "payload pointers", "confidence-tagged summaries"],
        ),
        ModuleCard(
            id="instinct-router",
            name="Instinct Router",
            zone_id="public",
            supervisor="hypervisor",
            stage="phase-2f",
            status="planned_shell",
            purpose="Turn novelty, anomaly, salience, urgency, and defer logic into routing and priority functions.",
            key_inputs=["sensory signals", "room events", "agent outputs", "circadian state"],
            outputs=["priority scores", "routing hints", "escalation recommendations"],
        ),
        ModuleCard(
            id="knowledge-graph",
            name="Knowledge Graph",
            zone_id="public",
            supervisor="knowledge supervisor",
            stage="planned",
            status="planned",
            purpose="Connect memories, media, biology, and public knowledge into explicit, evidence-linked relations.",
            key_inputs=["event links", "asset facts", "approved biological summaries"],
            outputs=["typed edges", "entity graph", "traceable evidence trails"],
        ),
        ModuleCard(
            id="structural-bio",
            name="Structural Bio Layer",
            zone_id="restricted_bio",
            supervisor="simulation supervisor",
            stage="planned",
            status="planned",
            purpose="Answer targeted structure and molecular questions only after supervisor approval and scope selection.",
            key_inputs=["selected targets", "known structures", "approved variant questions"],
            outputs=["structure notes", "simulation plans", "evidence-bound hypotheses"],
        ),
    ],
    agents=[
        AgentRole(
            id="hypervisor",
            name="Hypervisor",
            layer="shared",
            responsibility="Route work, enforce permissions, record audit, and keep room boundaries explicit.",
            watches=["policy engine", "approval gates", "audit log", "debug bridge"],
        ),
        AgentRole(
            id="teacher",
            name="Teacher and Evaluator",
            layer="shared",
            responsibility="Check results, surface weak evidence, and keep supervisors honest without becoming source truth.",
            watches=["confidence gaps", "evaluation failures", "routing drift"],
        ),
        AgentRole(
            id="media-supervisor",
            name="Media Supervisor",
            layer="domain",
            responsibility="Coordinate file ingest, metadata extraction, indexing, and future OCR/transcription workloads.",
            watches=["dataset intake", "failed imports", "asset metadata quality"],
        ),
        AgentRole(
            id="memory-supervisor",
            name="Memory Supervisor",
            layer="domain",
            responsibility="Coordinate raw event capture, episode construction, and evidence-backed retrieval.",
            watches=["timeline coverage", "event provenance", "episode uncertainty"],
        ),
        AgentRole(
            id="art-supervisor",
            name="Art Supervisor",
            layer="domain",
            responsibility="Oversee drawing metrics and visual analysis while blocking pseudo-clinical interpretation.",
            watches=["metric drift", "dataset quality", "formal feature coverage"],
        ),
        AgentRole(
            id="genomics-supervisor",
            name="Genomics Supervisor",
            layer="domain",
            responsibility="Gate all bio access, isolate raw intake, and approve only sandboxed summaries upstream.",
            watches=["restricted_bio access", "annotation provenance", "approval state"],
        ),
        AgentRole(
            id="simulation-supervisor",
            name="Simulation Supervisor",
            layer="domain",
            responsibility="Translate approved biology questions into targeted structure or modeling work.",
            watches=["scope control", "compute jobs", "result validity"],
        ),
        AgentRole(
            id="ingest-worker",
            name="Ingest Worker",
            layer="worker",
            responsibility="Scan local folders, classify files, hash content, and write indexed asset records.",
            watches=["file roots", "hashing pipeline", "dedup groundwork"],
        ),
    ],
    rooms=ROOM_REGISTRY,
    permission_levels=PERMISSION_LEVELS,
    build_phases=[
        BuildPhase(
            id="phase-1",
            title="Foundation",
            goal="Keep the shared cockpit, trust zones, supervisors, and policy map visible from day one.",
            deliverables=["mission control", "module registry", "trust zones", "owner debug visibility"],
        ),
        BuildPhase(
            id="phase-2a",
            title="Data Ingest Spine",
            goal="Index local datasets with recursive scanning, preflight manifest visibility, file classification, hashing, metadata extraction, and audit trails.",
            deliverables=["dataset intake", "preflight manifests", "asset index", "ingest runs", "audit entries"],
        ),
        BuildPhase(
            id="phase-2b",
            title="Memory and Timeline Spine",
            goal="Model raw events, entities, and episodes while keeping interpretations visibly linked to source truth.",
            deliverables=["event model", "entity model", "episode model", "memory search"],
        ),
        BuildPhase(
            id="phase-2c",
            title="Art and Drawing Metrics",
            goal="Measure formal properties of drawings and art without drifting into personality profiling.",
            deliverables=["figure count", "line density", "symmetry", "composition balance"],
        ),
        BuildPhase(
            id="phase-2d",
            title="Genomics Intake Sandbox",
            goal="Add raw intake, normalization, annotation sandboxing, and supervisor-gated summaries for genomics.",
            deliverables=["format recognition", "normalization", "annotation shell", "gated summaries"],
        ),
        BuildPhase(
            id="phase-2e",
            title="Constitution Layer Shell",
            goal="Prepare the stable substrate for long-cycle parameters, lineage references, provenance, and controlled mutation logs.",
            deliverables=["trait vectors", "bias parameters", "version history", "approval state"],
        ),
        BuildPhase(
            id="phase-2f",
            title="Circadian and Sensory Shells",
            goal="Create interfaces for circadian control, sensory channels, and instinct-style routing without overbuilding simulation.",
            deliverables=["circadian controls", "sensory channels", "instinct router", "maintenance windows"],
        ),
        BuildPhase(
            id="phase-3",
            title="Knowledge and Structural Expansion",
            goal="Grow the graph and targeted structural biology capabilities only after the governed intake layers are solid.",
            deliverables=["knowledge graph", "structure context", "approved molecular questions"],
        ),
        BuildPhase(
            id="phase-4",
            title="Clone Interaction Layer",
            goal="Render the clone as a supervised interface over all approved modules rather than a raw data lake.",
            deliverables=["identity rendering", "cross-module explanations", "safe multi-room collaboration"],
        ),
    ],
)
